version: '3.8'

services:
  # SIRAJ Educational AI Backend
  siraj-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siraj-educational-backend
    ports:
      - "8000:8000"
    environment:
      - SIRAJ_VERSION=8.1.0
      - SIRAJ_MODE=educational
      - OLLAMA_HOST=http://host.docker.internal:11434
      - GEMMA_PRIMARY_MODEL=gemma3n:e4b
      - GEMMA_LIGHTWEIGHT_MODEL=gemma3n:e2b
      - DATABASE_URL=postgresql://siraj_edu:secure_educational_ai_2024@postgres:5432/siraj_education
      - REDIS_URL=redis://redis:6379/0
      - MAX_CONCURRENT_SESSIONS=25
      - TEACHING_COUNCIL_SIZE=7
      - ADAPTIVE_LEARNING=true
      - MULTI_PERSPECTIVE_TEACHING=true
      - CURRICULUM_MAPPING=true
      - ASSESSMENT_GENERATION=true
      - LEARNING_ANALYTICS=true
    volumes:
      - ./backend:/app
      - siraj_logs:/app/logs
      - siraj_data:/app/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # SIRAJ Educational Frontend
  siraj-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: siraj-educational-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
      - REACT_APP_SIRAJ_VERSION=8.1.0
      - REACT_APP_MODE=educational
      - REACT_APP_ENABLE_ADAPTIVE=true
      - REACT_APP_ENABLE_ASSESSMENT=true
      - REACT_APP_ENABLE_MULTI_TEACHER=true
      - REACT_APP_MAX_SESSION_TIME=60
      - REACT_APP_COUNCIL_SIZE=7
    volumes:
      - ./frontend:/app
    depends_on:
      - siraj-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3

  # PostgreSQL Database for Educational Data
  postgres:
    image: postgres:15-alpine
    container_name: siraj-educational-database
    environment:
      - POSTGRES_DB=siraj_education
      - POSTGRES_USER=siraj_edu
      - POSTGRES_PASSWORD=secure_educational_ai_2024
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init_education_db.sql:/docker-entrypoint-initdb.d/01-init-education-db.sql
      - ./backend/sql/curriculum_standards.sql:/docker-entrypoint-initdb.d/02-curriculum-standards.sql
      - ./backend/sql/learning_analytics.sql:/docker-entrypoint-initdb.d/03-learning-analytics.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siraj_edu -d siraj_education"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for Session Management and Caching
  redis:
    image: redis:7-alpine
    container_name: siraj-educational-redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Educational Analytics Service (Optional)
  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    container_name: siraj-educational-analytics
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://siraj_edu:secure_educational_ai_2024@postgres:5432/siraj_education
      - REDIS_URL=redis://redis:6379/1
      - ANALYTICS_MODE=educational
    volumes:
      - ./analytics:/app
      - siraj_analytics_data:/app/data
    depends_on:
      - postgres
      - redis
      - siraj-backend
    restart: unless-stopped
    profiles:
      - analytics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: siraj-educational-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - siraj-frontend
      - siraj-backend
    restart: unless-stopped
    profiles:
      - production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Educational Content Management (Optional)
  content-manager:
    build:
      context: ./content-manager
      dockerfile: Dockerfile
    container_name: siraj-content-manager
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://siraj_edu:secure_educational_ai_2024@postgres:5432/siraj_education
      - STORAGE_PATH=/app/content
    volumes:
      - ./content-manager:/app
      - siraj_content_data:/app/content
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - content-management
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Model Download and Setup Service
  model-setup:
    image: alpine:latest
    container_name: siraj-model-setup
    volumes:
      - ./scripts:/scripts:ro
    command: >
      sh -c "
        echo 'Verifying Ollama models are available...' &&
        apk add --no-cache curl &&
        while ! curl -s http://host.docker.internal:11434/api/tags > /dev/null; do
          echo 'Waiting for Ollama service...' &&
          sleep 5
        done &&
        echo 'Ollama service is ready!' &&
        echo 'Educational AI models configured successfully.'
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - setup

# Named volumes for persistent data
volumes:
  postgres_data:
    driver: local
    name: siraj_postgres_data
  redis_data:
    driver: local
    name: siraj_redis_data
  siraj_logs:
    driver: local
    name: siraj_application_logs
  siraj_data:
    driver: local
    name: siraj_educational_data
  siraj_analytics_data:
    driver: local
    name: siraj_analytics_data
  siraj_content_data:
    driver: local
    name: siraj_content_data
  nginx_logs:
    driver: local
    name: siraj_nginx_logs

# Networks
networks:
  default:
    name: siraj-educational-network
    driver: bridge